import type { ChildSlittingOrder, MasterRoll } from '../../../types/slitting';
import type { TableColumnDef } from '../../table/FilterableTable';
import type { ColumnOption } from '../../table/useConfigurableColumns';

export const MASTER_COLUMN_OPTIONS: ColumnOption[] = [
  { key: 'rollCode', label: '母卷编码', required: true },
  { key: 'productCode', label: '物料规格' },
  { key: 'finishedProductCode', label: 'BOM 根' },
  { key: 'widthMm', label: '宽度 (mm)' },
  { key: 'lengthMm', label: '长度 (mm)' },
  { key: 'thicknessMm', label: '厚度 (mm)' },
  { key: 'materialCode', label: '材质' },
  { key: 'kerfLongitudinalMm', label: '纵向切边 (mm)' },
  { key: 'kerfTransverseMm', label: '横向切边 (mm)' },
  { key: 'status', label: '状态' },
];

export const MASTER_DEFAULT_VISIBLE = [
  'rollCode',
  'productCode',
  'widthMm',
  'lengthMm',
  'materialCode',
  'status',
];

export const ORDER_COLUMN_OPTIONS: ColumnOption[] = [
  { key: 'orderCode', label: '订单编码', required: true },
  { key: 'productCode', label: '物料规格' },
  { key: 'finishedProductCode', label: 'BOM 根' },
  { key: 'widthMm', label: '宽度 (mm)' },
  { key: 'lengthMm', label: '长度 (mm)' },
  { key: 'thicknessMm', label: '厚度 (mm)' },
  { key: 'quantity', label: '数量' },
  { key: 'priority', label: '优先级' },
  { key: 'salesOrderNo', label: '销售订单' },
  { key: 'salesOrderLineNo', label: '销售行号' },
  { key: 'workOrderNo', label: '工单号' },
  { key: 'status', label: '状态' },
];

export const ORDER_DEFAULT_VISIBLE = [
  'orderCode',
  'productCode',
  'widthMm',
  'lengthMm',
  'thicknessMm',
  'quantity',
  'priority',
  'salesOrderNo',
  'workOrderNo',
  'status',
];

const fmt = (v: string | number | undefined | null) =>
  v === undefined || v === null || v === '' ? '—' : String(v);

export const MASTER_COLUMNS: TableColumnDef<MasterRoll>[] = [
  {
    key: 'productCode',
    header: '物料规格',
    defaultWidth: 140,
    filterable: false,
    render: (r) => r.productCode ?? '—',
    getFilterText: (r) => r.productCode ?? '',
  },
  {
    key: 'finishedProductCode',
    header: 'BOM 根',
    defaultWidth: 120,
    filterable: false,
    render: (r) => r.finishedProductCode ?? '—',
    getFilterText: (r) => r.finishedProductCode ?? '',
  },
  {
    key: 'rollCode',
    header: '母卷编码',
    defaultWidth: 120,
    minWidth: 88,
    filterable: false,
    render: (r) => r.rollCode,
    getFilterText: (r) => r.rollCode,
  },
  {
    key: 'widthMm',
    header: '宽度 (mm)',
    defaultWidth: 88,
    align: 'right',
    filterable: false,
    render: (r) => r.widthMm,
    getFilterText: (r) => String(r.widthMm),
  },
  {
    key: 'lengthMm',
    header: '长度 (mm)',
    defaultWidth: 88,
    align: 'right',
    filterable: false,
    render: (r) => r.lengthMm,
    getFilterText: (r) => String(r.lengthMm),
  },
  {
    key: 'thicknessMm',
    header: '厚度 (mm)',
    defaultWidth: 80,
    align: 'right',
    filterable: false,
    render: (r) => fmt(r.thicknessMm),
    getFilterText: (r) => fmt(r.thicknessMm),
  },
  {
    key: 'materialCode',
    header: '材质',
    defaultWidth: 72,
    filterable: false,
    render: (r) => fmt(r.materialCode),
    getFilterText: (r) => fmt(r.materialCode),
  },
  {
    key: 'kerfLongitudinalMm',
    header: '纵向切边',
    defaultWidth: 80,
    align: 'right',
    filterable: false,
    render: (r) => r.kerfLongitudinalMm,
    getFilterText: (r) => String(r.kerfLongitudinalMm),
  },
  {
    key: 'kerfTransverseMm',
    header: '横向切边',
    defaultWidth: 80,
    align: 'right',
    filterable: false,
    render: (r) => r.kerfTransverseMm,
    getFilterText: (r) => String(r.kerfTransverseMm),
  },
  {
    key: 'status',
    header: '状态',
    defaultWidth: 72,
    filterable: false,
    render: (r) => r.status,
    getFilterText: (r) => r.status,
  },
];

export const ORDER_COLUMNS: TableColumnDef<ChildSlittingOrder>[] = [
  {
    key: 'orderCode',
    header: '订单编码',
    defaultWidth: 110,
    minWidth: 88,
    sortable: true,
    render: (r) => r.orderCode,
    getFilterText: (r) => r.orderCode,
    getSortValue: (r) => r.orderCode,
  },
  {
    key: 'productCode',
    header: '物料规格',
    defaultWidth: 130,
    sortable: true,
    render: (r) => r.productCode ?? '—',
    getFilterText: (r) => r.productCode ?? '',
    getSortValue: (r) => r.productCode ?? '',
  },
  {
    key: 'finishedProductCode',
    header: 'BOM 根',
    defaultWidth: 120,
    sortable: true,
    render: (r) => r.finishedProductCode ?? '—',
    getFilterText: (r) => r.finishedProductCode ?? '',
    getSortValue: (r) => r.finishedProductCode ?? '',
  },
  {
    key: 'widthMm',
    header: '宽度 (mm)',
    defaultWidth: 84,
    align: 'right',
    sortable: true,
    render: (r) => r.widthMm,
    getFilterText: (r) => String(r.widthMm),
    getSortValue: (r) => r.widthMm,
  },
  {
    key: 'lengthMm',
    header: '长度 (mm)',
    defaultWidth: 84,
    align: 'right',
    sortable: true,
    render: (r) => r.lengthMm,
    getFilterText: (r) => String(r.lengthMm),
    getSortValue: (r) => r.lengthMm,
  },
  {
    key: 'thicknessMm',
    header: '厚度 (mm)',
    defaultWidth: 76,
    align: 'right',
    sortable: true,
    render: (r) => fmt(r.thicknessMm),
    getFilterText: (r) => fmt(r.thicknessMm),
    getSortValue: (r) => r.thicknessMm ?? 0,
  },
  {
    key: 'quantity',
    header: '数量',
    defaultWidth: 64,
    align: 'right',
    sortable: true,
    render: (r) => r.quantity,
    getFilterText: (r) => String(r.quantity),
    getSortValue: (r) => r.quantity,
  },
  {
    key: 'priority',
    header: '优先级',
    defaultWidth: 68,
    align: 'right',
    sortable: true,
    render: (r) => r.priority,
    getFilterText: (r) => String(r.priority),
    getSortValue: (r) => r.priority,
  },
  {
    key: 'salesOrderNo',
    header: '销售订单',
    defaultWidth: 100,
    sortable: true,
    render: (r) => fmt(r.salesOrderNo),
    getFilterText: (r) => fmt(r.salesOrderNo),
    getSortValue: (r) => fmt(r.salesOrderNo),
  },
  {
    key: 'salesOrderLineNo',
    header: '销售行号',
    defaultWidth: 72,
    align: 'right',
    sortable: true,
    render: (r) => fmt(r.salesOrderLineNo),
    getFilterText: (r) => fmt(r.salesOrderLineNo),
    getSortValue: (r) => r.salesOrderLineNo ?? 0,
  },
  {
    key: 'workOrderNo',
    header: '工单号',
    defaultWidth: 96,
    sortable: true,
    render: (r) => fmt(r.workOrderNo),
    getFilterText: (r) => fmt(r.workOrderNo),
    getSortValue: (r) => fmt(r.workOrderNo),
  },
  {
    key: 'status',
    header: '状态',
    defaultWidth: 72,
    sortable: true,
    render: (r) => r.status,
    getFilterText: (r) => r.status,
    getSortValue: (r) => r.status,
  },
];

export function pickColumns<T>(all: TableColumnDef<T>[], visibleKeys: string[]): TableColumnDef<T>[] {
  return visibleKeys
    .map((key) => all.find((c) => c.key === key))
    .filter((c): c is TableColumnDef<T> => c != null);
}
