-- V11_1 未命中 H2 自动生成的约束名，旧「仅业务键」唯一约束仍在，导致无法按 workspace 写入系统参数等
-- 本脚本删除遗留唯一约束；组合唯一索引 uk_*_ws 已在 V11_1 创建

ALTER TABLE system_parameter DROP CONSTRAINT IF EXISTS CONSTRAINT_7A_INDEX_7;
ALTER TABLE system_parameter DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_15;

ALTER TABLE sales_order_line DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_2;

ALTER TABLE production_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_3;
ALTER TABLE production_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_4;

ALTER TABLE product_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_5;
ALTER TABLE product_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_6;

ALTER TABLE shift_headcount DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_7;
ALTER TABLE shift_headcount DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_8;

ALTER TABLE production_line DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_9;
ALTER TABLE production_line DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_A;

ALTER TABLE changeover_matrix DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_A;
ALTER TABLE changeover_matrix DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_B;

ALTER TABLE work_order DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_C;
ALTER TABLE work_order DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_D;

ALTER TABLE plan_version DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_E;
ALTER TABLE plan_version DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_F;

ALTER TABLE shortage_recommendation DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_11;
ALTER TABLE shortage_recommendation DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_12;

ALTER TABLE planning_event DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_13;
ALTER TABLE planning_event DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_14;

ALTER TABLE planning_pipeline_run DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_17;
ALTER TABLE planning_pipeline_run DROP CONSTRAINT IF EXISTS CONSTRAINT_INDEX_18;
