-- H2 唯一约束名与索引名不同（如 CONSTRAINT_55 / CONSTRAINT_55_INDEX_B），须 DROP CONSTRAINT
-- 名称来自 INFORMATION_SCHEMA.TABLE_CONSTRAINTS（uk_*_ws 保留）

ALTER TABLE sales_order_line DROP CONSTRAINT IF EXISTS CONSTRAINT_55;
ALTER TABLE production_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_F3;
ALTER TABLE product_resource DROP CONSTRAINT IF EXISTS CONSTRAINT_21C;
ALTER TABLE shift_headcount DROP CONSTRAINT IF EXISTS CONSTRAINT_E2;
ALTER TABLE production_line DROP CONSTRAINT IF EXISTS CONSTRAINT_95;
ALTER TABLE changeover_matrix DROP CONSTRAINT IF EXISTS CONSTRAINT_D1;
ALTER TABLE work_order DROP CONSTRAINT IF EXISTS CONSTRAINT_32;
ALTER TABLE plan_version DROP CONSTRAINT IF EXISTS CONSTRAINT_9B3;
ALTER TABLE shortage_recommendation DROP CONSTRAINT IF EXISTS CONSTRAINT_223;
ALTER TABLE planning_event DROP CONSTRAINT IF EXISTS CONSTRAINT_646;
ALTER TABLE system_parameter DROP CONSTRAINT IF EXISTS CONSTRAINT_7A;
ALTER TABLE planning_pipeline_run DROP CONSTRAINT IF EXISTS CONSTRAINT_DE9;
