-- PanacheEntity 使用 <table>_SEQ；V18 表为 AUTO_INCREMENT 时需补序列
CREATE SEQUENCE IF NOT EXISTS rule_set_version_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS planning_scenario_SEQ START WITH 1 INCREMENT BY 50;
