-- PanacheEntity 使用 *_SEQ；V49 表为 BIGSERIAL 时需补序列
CREATE SEQUENCE IF NOT EXISTS master_roll_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS child_slitting_order_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS intermediate_roll_catalog_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS slitting_plan_version_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS slitting_plan_master_roll_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS slitting_plan_child_order_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS slitting_roll_node_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS slitting_assignment_SEQ START WITH 1 INCREMENT BY 50;

-- V49_1 demo 已占用小 id，避免 Panache 序列与种子主键冲突
ALTER SEQUENCE master_roll_SEQ RESTART WITH 100;
ALTER SEQUENCE child_slitting_order_SEQ RESTART WITH 100;
ALTER SEQUENCE intermediate_roll_catalog_SEQ RESTART WITH 100;
